version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: teste_kanastra
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: /bin/sh -c 'chmod -R 777 /var/www/html/storage/* /var/www/html/bootstrap/cache/* && chown -R www-data:www-data /var/www/html/storage/* /var/www/html/bootstrap/cache/* && apache2-foreground & php artisan queue:work'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 1024M
  db:
    image: mysql:8.0
    container_name: mysql_kanastra
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kanastra_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 1024M

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    container_name: redis_kanastra
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=511
    networks:
      - app-network

  boleto_listener:
    build:
      context: .
      dockerfile: ./python/boleto/Dockerfile
    networks:
      - app-network
    volumes:
      - ./python/boleto/src:/app 

  email_sender:
    build:
      context: .
      dockerfile: ./python/email/Dockerfile
    volumes:
      - ./python/email/src:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
